name: "[Tests] Acceptance Testing"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    uses: istic/shared-workflows/.github/workflows/laravel-tests.yml@main
    with:
      php_version: "8.4"
      node_version: "20"
      has_dusk: true
      test_command: "vendor/bin/phpunit"
    secrets: inherit # pragma: allowlist secret
